services:
  db:
    image: mysql:8.0
    container_name: ${APP_NAME}_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  dolibarr:
    image: dolibarr/dolibarr:21
    container_name: ${APP_NAME}_app
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      DOLI_DB_HOST: db
      DOLI_DB_NAME: ${DOLI_DB_NAME}
      DOLI_DB_USER: ${DOLI_DB_USER}
      DOLI_DB_PASSWORD: ${DOLI_DB_PASSWORD}
      DOLI_ADMIN_LOGIN: ${DOLI_ADMIN_LOGIN}
      DOLI_ADMIN_PASSWORD: ${DOLI_ADMIN_PASSWORD}
      WWW_USER_ID: ${WWW_USER_ID}
      WWW_GROUP_ID: ${WWW_GROUP_ID}
    volumes:
      - /home/rocken/dolibarrs/${APP_NAME}/custom:/var/www/html/custom

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_pma
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${DOLI_DB_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  grafana:
    image: grafana/grafana
    container_name: ${APP_NAME}_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: ${APP_NAME}_prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node_exporter
    restart: always
    ports:
      - "9100:9100"

volumes:
  db_data:
  grafana_data: